### ISSUE TITLE
ansible-navigator inventory -i ../hosts crashes

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#106]
ProductName:	macOS
ProductVersion:	11.2.1
BuildVersion:	20D74

Python 3.9.2
ansible-navigator 0.6.0

../hosts contains:

[kindle]
192.168.123.111

[kindle:vars]
banter="Ok kindle. Let's automate!"
voice="Daniel"

[all:children]
kindle

pressing 1 to see the hosts crashes:
Traceback (most recent call last):
  File "/Users/pgriffit/ansible-navigator_demo/venv/bin/ansible-navigator", line 8, in <module>
    sys.exit(main())
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/cli.py", line 327, in main
    run(args)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/cli.py", line 293, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/action_runner.py", line 51, in run
    self._run_app(interaction)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/action_runner.py", line 60, in _run_app
    interaction = run_action(
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/actions/_actions.py", line 68, in call
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/actions/inventory.py", line 196, in run
    self._take_step()
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/actions/inventory.py", line 244, in _take_step
    result = self._interaction.ui.show(
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/ui_framework/ui.py", line 855, in show
    result = self._show_menu(obj, columns, await_input)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/ui_framework/ui.py", line 790, in _show_menu
    menu_heading, menu_lines = self._get_heading_menu_items(current, columns, showing_idxs)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/ui_framework/ui.py", line 750, in _get_heading_menu_items
    menu_heading, menu_items = menu_builder.build(
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/ui_framework/menu_builder.py", line 39, in build
    return self._menu(dicts, cols, indicies)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/ui_framework/menu_builder.py", line 56, in _menu
    convert_percentage(dicts[idx], cols, self._pbar_width)
  File "/Users/pgriffit/ansible-navigator_demo/venv/lib/python3.9/site-packages/ansible_navigator/ui_framework/utils.py", line 23, in convert_percentage
    value = dyct[key]
KeyError: 'ansible_network_os'

Also crashes when selecting groups and selecting the first one.

**Comment by cidrblock** [comment]
I suspect this issue was fixed earlier when inventory columns were set by a settings file and hosts didn't have these attributes.

ansible-navigator will now show "None" for these columns
