### ISSUE TITLE
py311: failure to install on ubuntu

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-navigator#1248]
```
py311 installdeps: .[test]
ERROR: invocation failed (exit code 1), logfile: /media/psf/c/a/ansible-navigator/.tox/u1/py311/log/py311-1.log
======================================================================================= log start =======================================================================================
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/media/psf/c/a/ansible-navigator/.tox/u1/py311/lib/python3.11/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

Likely caused by https://github.com/pypa/pip/issues/11103

**Comment by cidrblock** [comment]
Not an issue, ubuntu running        3.11 in CI
