### ISSUE TITLE
ansible-navigator searches terminal_colors.json at the wrong place when running in virtualenv

### ISSUE THREAD

**Issue by ericzolf** [ansible/ansible-navigator#1446]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

I've just created a fresh virtualenv and installed ansible-navigator in it and the command `ansible-navigator images` fails with the message `FileNotFoundError: [Errno 2] No such file or directory: '/home/myuser/.local/share/ansible_navigator/themes/terminal_colors.json`, which is correct because the file is at `.../ansivenv/share/ansible_navigator/themes/terminal_colors.json`.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 2.2.0
```

##### CONFIGURATION

n/a

##### LOG FILE

```
$ ansible-navigator images
--------------------------------------------------------------------
Execution environment image and pull policy overview
--------------------------------------------------------------------
Execution environment image name:     quay.io/ansible/creator-ee:v0.9.1
Execution environment image tag:      v0.9.1
Execution environment pull arguments: None
Execution environment pull policy:    tag
Execution environment pull needed:    True
--------------------------------------------------------------------
Updating the execution environment
--------------------------------------------------------------------
Running the command: podman pull quay.io/ansible/creator-ee:v0.9.1
Trying to pull quay.io/ansible/creator-ee:v0.9.1...
Getting image source signatures
Copying blob fee18ea417d6 done  
[...]
Copying config d1524b4410 done  
Writing manifest to image destination
Storing signatures
d1524b4410d034b784fc0f32d6051cf384f676b16d690286297374923014cfd4
Traceback (most recent call last):
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/bin/ansible-navigator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/lib64/python3.11/site-packages/ansible_navigator/cli.py", line 159, in main
    run_return = run(args)
                 ^^^^^^^^^
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/lib64/python3.11/site-packages/ansible_navigator/cli.py", line 97, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/lib64/python3.11/site-packages/ansible_navigator/action_runner.py", line 90, in run
    self.initialize_ui(DEFAULT_REFRESH)
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/lib64/python3.11/site-packages/ansible_navigator/action_runner.py", line 73, in initialize_ui
    self._ui = UserInterface(
               ^^^^^^^^^^^^^^
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/lib64/python3.11/site-packages/ansible_navigator/ui_framework/ui.py", line 163, in __init__
    super().__init__(ui_config=ui_config)
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/lib64/python3.11/site-packages/ansible_navigator/ui_framework/curses_window.py", line 64, in __init__
    self._set_colors()
  File "/home/elavarde/Documents/Work/Ansible/ansivenv/lib64/python3.11/site-packages/ansible_navigator/ui_framework/curses_window.py", line 198, in _set_colors
    with open(self._ui_config.terminal_colors_path, encoding="utf-8") as fh:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/elavarde/.local/share/ansible_navigator/themes/terminal_colors.json'
```
##### STEPS TO REPRODUCE

```
python -m venv ansivenv
source ansivenv/bin/activate
pip install ansible-navigator
pip install --upgrade pip  # probably not relevant, just for sake of completeness
cd ansivenv/
ansible-navigator images
```

##### EXPECTED RESULTS

a list of images

##### ACTUAL RESULTS

see above

##### ADDITIONAL INFORMATION

It looks very much too me like a wrong assumption where the `share_directory` is supposed to be, but I don't follow the code, sorry. Wouldn't it be better to use https://setuptools.pypa.io/en/latest/pkg_resources.html#resourcemanager-api to access the file?

Anyway, after calling `ln -s .../ansivenv/share/ansible* ~/.local/share/`, the command `ansible-navigator images` did work properly, but that's obviously not a good approach (and allows only one virtualenv at once).

**Comment by cidrblock** [comment]
Can you try install from source?  These code paths have been changed significantly since 2.2.0...

LMK, TY, brad

**Comment by ssbarnea** [comment]
Closing due to lack of response.
