### ISSUE TITLE
ansible-navigator cannot handle long python METADATA.

### ISSUE THREAD

**Issue by mahoutukaisali** [ansible/ansible-navigator#1548]
## Issue
ansible-navigator cannot handle python METADATA license section(https://packaging.python.org/en/latest/specifications/core-metadata/#license) if it's written with long text.

## Steps to reproduce
1. Build a container image with the below files.

execution-environment.yml 
```
---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest'

ansible_config: '/etc/ansible/ansible.cfg'

dependencies:
  python: requirements.txt
```
requirements.txt
```
boto
boto3
botocore
file-magic
```

2. Run ansible-builder in the directory where the above files exist.
`$ ansible-builder build`

3. After an image build, run `ansible-navigator` command, select an image built with the above, then select `3 Python Packages` on `ansible-navigator` CLI. The issue will be happened with the below messages outputted in `ansible-navigator.log` file.

```
2023-05-30T07:22:12.051851+00:00 CRITICAL 'ansible_navigator.actions._actions.run_interactive' Subcommand 'select' encountered a fatal error.
2023-05-30T07:22:12.052365+00:00 ERROR 'ansible_navigator.actions._actions.run_interactive' Logging an uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ansible_navigator/actions/_actions.py", line 157, in run_interactive
    return run_action(app=app, interaction=interaction)
  File "/usr/lib/python3.9/site-packages/ansible_navigator/actions/select.py", line 40, in run
    app.steps.append(app.steps.current.select_func())  # add next
  File "/usr/lib/python3.9/site-packages/ansible_navigator/actions/images.py", line 321, in _build_image_content
    self._images.selected["python"]["details"],
KeyError: 'details'
```

To avoid the issue, try removing `file-magic` from requirements.txt file. 

FYI: Here, `file-magic` has long text.
$ python3 -m pip show file-magic
```
Name: file-magic
Version: 0.4.1
Summary: Python front end for libmagic(3)
Home-page: https://github.com/file/file
Author: Reuben Thomas, Álvaro Justen
Author-email: Christos Zoulas <christos@astron.com>
License: Copyright (c) Ian F. Darwin 1986-1995.
        Software written by Ian F. Darwin and others;
        maintained 1995-present by Christos Zoulas and others.        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions
        are met:
        1. Redistributions of source code must retain the above copyright
           notice immediately at the beginning of the file, without modification,
           this list of conditions, and the following disclaimer.
        2. Redistributions in binary form must reproduce the above copyright
           notice, this list of conditions and the following disclaimer in the
           documentation and/or other materials provided with the distribution.        
        THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
        ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
        ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
        ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
        OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
        HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
        LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
        OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
        SUCH DAMAGE.        
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by: 
```

## Expected behavior
The issue doesn't occur even though container images include python packages that have long text python METADATA.

**Comment by cidrblock** [comment]
TY for this, we'll look into it!
