### ISSUE TITLE
Can't install ansible-navigator via setup instructions ModuleNotFoundError: No module named 'python-owasp-zap-v2' 

### ISSUE THREAD

**Issue by jmaks** [ansible/ansible-navigator#1553]
##### ISSUE TYPE

- Bug Report

##### SUMMARY
Got make installation steps via official documentation. When trying to start an application got an error of missed modules and dependecies 

python3 version
```
 python -V
Python 3.11.2
```
pip3 version
```
pip3 --version                                
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)

```

OS version
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator --help   
Traceback (most recent call last):
  File "/home/user/.local/bin/ansible-navigator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/cli.py", line 140, in main
    messages: list[LogMessage] = log_dependencies()
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/cli.py", line 83, in log_dependencies
    spec = find_spec(pkg_name)
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 94, in find_spec
ModuleNotFoundError: No module named 'python-owasp-zap-v2'

```

Installation from packages via pip3
```
pip3 install 'ansible-navigator[ansible-core]'
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ansible-navigator[ansible-core] in /home/user/.local/lib/python3.11/site-packages (3.4.0)
WARNING: ansible-navigator 3.4.0 does not provide the extra 'ansible-core'
Requirement already satisfied: ansible-builder>=3.0.0 in /home/user/.local/lib/python3.11/site-packages (from ansible-navigator[ansible-core]) (3.0.0)
Requirement already satisfied: ansible-runner<3,>=2.3.1 in /home/user/.local/lib/python3.11/site-packages (from ansible-navigator[ansible-core]) (2.3.3)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from ansible-navigator[ansible-core]) (3.0.3)
Requirement already satisfied: jsonschema in /usr/lib/python3/dist-packages (from ansible-navigator[ansible-core]) (4.10.3)
Requirement already satisfied: onigurumacffi<2,>=1.1.0 in /home/user/.local/lib/python3.11/site-packages (from ansible-navigator[ansible-core]) (1.2.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from ansible-navigator[ansible-core]) (6.0)
Requirement already satisfied: tzdata in /home/user/.local/lib/python3.11/site-packages (from ansible-navigator[ansible-core]) (2023.3)
Requirement already satisfied: setuptools>=63.1.0 in /usr/lib/python3/dist-packages (from ansible-navigator[ansible-core]) (66.1.1)
Requirement already satisfied: requirements-parser in /home/user/.local/lib/python3.11/site-packages (from ansible-builder>=3.0.0->ansible-navigator[ansible-core]) (0.5.0)
Requirement already satisfied: bindep in /home/user/.local/lib/python3.11/site-packages (from ansible-builder>=3.0.0->ansible-navigator[ansible-core]) (2.11.0)
Requirement already satisfied: pexpect>=4.5 in /usr/lib/python3/dist-packages (from ansible-runner<3,>=2.3.1->ansible-navigator[ansible-core]) (4.8.0)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from ansible-runner<3,>=2.3.1->ansible-navigator[ansible-core]) (23.0)
Requirement already satisfied: python-daemon in /home/user/.local/lib/python3.11/site-packages (from ansible-runner<3,>=2.3.1->ansible-navigator[ansible-core]) (3.0.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from ansible-runner<3,>=2.3.1->ansible-navigator[ansible-core]) (1.16.0)
Requirement already satisfied: cffi>=1 in /usr/lib/python3/dist-packages (from onigurumacffi<2,>=1.1.0->ansible-navigator[ansible-core]) (1.15.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from jsonschema->ansible-navigator[ansible-core]) (22.2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/lib/python3/dist-packages (from jsonschema->ansible-navigator[ansible-core]) (0.18.1)
Requirement already satisfied: Parsley in /home/user/.local/lib/python3.11/site-packages (from bindep->ansible-builder>=3.0.0->ansible-navigator[ansible-core]) (1.3)
Requirement already satisfied: pbr>=2.0.0 in /home/user/.local/lib/python3.11/site-packages (from bindep->ansible-builder>=3.0.0->ansible-navigator[ansible-core]) (5.11.1)
Requirement already satisfied: distro>=1.7.0 in /usr/lib/python3/dist-packages (from bindep->ansible-builder>=3.0.0->ansible-navigator[ansible-core]) (1.8.0)
Requirement already satisfied: docutils in /usr/lib/python3/dist-packages (from python-daemon->ansible-runner<3,>=2.3.1->ansible-navigator[ansible-core]) (0.19)
Requirement already satisfied: lockfile>=0.10 in /home/user/.local/lib/python3.11/site-packages (from python-daemon->ansible-runner<3,>=2.3.1->ansible-navigator[ansible-core]) (0.12.2)
Requirement already satisfied: types-setuptools>=57.0.0 in /home/user/.local/lib/python3.11/site-packages (from requirements-parser->ansible-builder>=3.0.0->ansible-navigator[ansible-core]) (67.8.0.0)
```

##### STEPS TO REPRODUCE

install python3.11
install python3-pip
install ansible-navigator
try to start app

##### EXPECTED RESULTS

Working app.

##### ACTUAL RESULTS

Got an incomprehensible and unsolvable  trouble.

**Comment by cidrblock** [comment]
Thanks.

We can wrap that in an try/except loop to avoid the error.

**Comment by jmaks** [comment]
Got checked patch. 
All works fine. Sup
