### ISSUE TITLE
Error while viewing collection in a EE created by ansible-builder 3.0

### ISSUE THREAD

**Issue by olivierlemasle** [ansible/ansible-navigator#1582]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

Doing `ansible-navigator collections` with an Execution Environment created with `ansible-builder` (cf configuration below) fails with 2 warning messages.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 3.4.0
```

##### CONFIGURATION

N/A (default ansible-navigator configuration)

##### LOG FILE

```
2023-07-23T16:35:19.370723+00:00 ERROR 'ansible_navigator.actions.collections._run_runner' Traceback (most recent call last):
  File "/home/user/.cache/ansible-navigator/catalog_collections.py", line 23, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

2023-07-23T16:35:49.811736+00:00 ERROR 'ansible_navigator.actions.collections._parse' Unable to extract collection json from stdout
```

##### STEPS TO REPRODUCE

1. Create a EE image `localhost/ee:0.0.1` as follow:
   1. Create a file `execution-environment.yml` with content:
      
      ```
      ---
      version: 3
      
      images:
        base_image:
          name: quay.io/fedora/python-311:latest
      
      dependencies:
        ansible_core:
          package_pip: ansible-core
        ansible_runner:
          package_pip: ansible-runner
        galaxy:
          collections:
            - community.general
        python:
          - ansible-lint
      ```

   1. Build the EE with `ansible-builder 3.0.0`:

      ```
      ansible-builder build -t ee:0.0.1
      ```
1. Execute `ansible-navigator --eei localhost/ee:0.0.1 collections`

##### EXPECTED RESULTS

I expect the browsing into the EEI collections.

##### ACTUAL RESULTS

First a warning message:

```
Warning
──────────────────────────────────────────────────────────────────
humph. Something went really wrong while cataloging collections.
Details have been added to the log file
[HINT] Please log an issue about this one, it shouldn't have
happened
```

Then another:

```
Warning
──────────────────────────────────────────────────────────
humph. no collections were found in the following paths:
[HINT] Try installing some or try a different execution
environment
```

(cf log file above)

##### ADDITIONAL INFORMATION
In `stdout` mode, I get another error:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/ansible-navigator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/cli.py", line 192, in main
    run_return = run(args)
                 ^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/cli.py", line 120, in run
    result = run_action_stdout(args.app.replace("-", "_"), args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/actions/_actions.py", line 185, in run_stdout
    return action_cls(args).run_stdout()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/actions/collections.py", line 198, in run_stdout
    self._run_runner()
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/actions/collections.py", line 503, in _run_runner
    self.notify_failed()
  File "/home/user/.local/lib/python3.11/site-packages/ansible_navigator/actions/collections.py", line 221, in notify_failed
    self._interaction.ui.show_form(warning)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Action' object has no attribute '_interaction'
```

However, `ansible-navigator run` and `ansible-navigator doc` work, and the collection is used.

E.g.:

```
ansible-navigator --eei localhost/ee:0.0.1 -m stdout doc -l
```

**Comment by olivierlemasle** [comment]
I confirm that the issue occurs with the image created with the `execution-environment.yml` above, but not with all images created by ansible-builder.

Eg. with the following `execution-environment.yml`, I've got no issue:

```yaml
---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora-minimal:38

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  python_interpreter:
    package_system: python3
  ansible_core:
    package_pip: ansible-core==2.15.2
  ansible_runner:
    package_pip: ansible-runner==2.3.1
  galaxy: requirements.yml
  python:
    - ansible-lint
  system:
    - less
    - ssh

```

**Comment by shatakshiiii** [comment]
Hey @olivierlemasle, Thanks for reporting this issue and all the additional information, we will look into it.
