### ISSUE TITLE
issue exploring collections

### ISSUE THREAD

**Issue by abikouo** [ansible/ansible-navigator#241]
ansible-navigator raised an exception when exploring collection without execution environment

``ansible-navigator  --execution-environment false collections``

Here is the output

```
Traceback (most recent call last):
  File "/home/aubin/work/env/py3/bin/ansible-navigator", line 8, in <module>
    sys.exit(main())
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/cli.py", line 104, in main
    run(args)
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/cli.py", line 54, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/action_runner.py", line 50, in run
    self._run_app(interaction)
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/action_runner.py", line 59, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/actions/_actions.py", line 95, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/actions/collections.py", line 118, in run
    self._run_runner()
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/actions/collections.py", line 314, in _run_runner
    self._parse(output)
  File "/home/aubin/work/env/py3/lib64/python3.9/site-packages/ansible_navigator/actions/collections.py", line 343, in _parse
    collection["__version"] = collection["collection_info"]["version"]
KeyError: 'version'
```

**Comment by cidrblock** [comment]
This can default to "missing" if the key is missing, ty
