### ISSUE TITLE
Periodic test failures due to runner issue

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#271]
https://github.com/ansible/ansible-runner/issues/694

recheck usually gets through this

```
2021-05-15 16:08:42.659697 | ubuntu-bionic | E       +******** ERROR: TMUX RESPONSE TIMEOUT @ 60.006299034999984s @ 2021-05-15T16:06:44.833441+00:00 ********
2021-05-15 16:08:42.659708 | ubuntu-bionic | E       +******** Captured to: /home/zuul/zuul-output/logs/anible-navigator/tests/integration/actions/collections/test_direct_interactive_ee.py/showing_timeout.txt
2021-05-15 16:08:42.659718 | ubuntu-bionic | E       +Traceback (most recent call last):
2021-05-15 16:08:42.659760 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/bin/ansible-navigator", line 8, in <module>
2021-05-15 16:08:42.659781 | ubuntu-bionic | E       +    sys.exit(main())
2021-05-15 16:08:42.659791 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/cli.py", line 104, in main
2021-05-15 16:08:42.659801 | ubuntu-bionic | E       +    run(args)
2021-05-15 16:08:42.659810 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/cli.py", line 54, in run
2021-05-15 16:08:42.659820 | ubuntu-bionic | E       +    wrapper(ActionRunner(args=args).run)
2021-05-15 16:08:42.659840 | ubuntu-bionic | E       +  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
2021-05-15 16:08:42.659851 | ubuntu-bionic | E       +    return func(stdscr, *args, **kwds)
2021-05-15 16:08:42.659860 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 50, in run
2021-05-15 16:08:42.659876 | ubuntu-bionic | E       +    self._run_app(interaction)
2021-05-15 16:08:42.659886 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 59, in _run_app
2021-05-15 16:08:42.659895 | ubuntu-bionic | E       +    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
2021-05-15 16:08:42.659905 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/actions/_actions.py", line 95, in run_interactive
2021-05-15 16:08:42.659915 | ubuntu-bionic | E       +    return action_cls(app.args).run(app=app, interaction=interaction)
2021-05-15 16:08:42.659924 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/actions/collections.py", line 118, in run
2021-05-15 16:08:42.659933 | ubuntu-bionic | E       +    self._run_runner()
2021-05-15 16:08:42.659942 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/actions/collections.py", line 308, in _run_runner
2021-05-15 16:08:42.659958 | ubuntu-bionic | E       +    output, error = _runner.run()
2021-05-15 16:08:42.659968 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_navigator/runner/api.py", line 232, in run
2021-05-15 16:08:42.659977 | ubuntu-bionic | E       +    out, err = run_command(**self._runner_args)
2021-05-15 16:08:42.659986 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_runner/interface.py", line 372, in run_command
2021-05-15 16:08:42.659996 | ubuntu-bionic | E       +    r = init_command_config(executable_cmd, cmdline_args=cmdline_args, **kwargs)
2021-05-15 16:08:42.660005 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_runner/interface.py", line 282, in init_command_config
2021-05-15 16:08:42.660015 | ubuntu-bionic | E       +    rc = CommandConfig(**kwargs)
2021-05-15 16:08:42.660038 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_runner/config/command.py", line 61, in __init__
2021-05-15 16:08:42.660049 | ubuntu-bionic | E       +    super(CommandConfig, self).__init__(**kwargs)
2021-05-15 16:08:42.660059 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/site-packages/ansible_runner/config/_base.py", line 122, in __init__
2021-05-15 16:08:42.660068 | ubuntu-bionic | E       +    os.makedirs(self.private_data_dir, mode=0o700)
2021-05-15 16:08:42.660077 | ubuntu-bionic | E       +  File "/home/zuul/src/github.com/ansible/ansible-navigator/.tox/py38/lib/python3.6/os.py", line 220, in makedirs
2021-05-15 16:08:42.660087 | ubuntu-bionic | E       +    mkdir(name, mode)
2021-05-15 16:08:42.660096 | ubuntu-bionic | E       +FileExistsError: [Errno 17] File exists: '/home/zuul/.ansible-runner'
2021-05-15 16:08:42.660105 | ubuntu-bionic | E       +(py38) bash-4.4$
```

**Comment by cidrblock** [comment]
The use of temp + uuid eliminates this as an issue for ansible-navigator
