### ISSUE TITLE
[:ee-details] ignore_errors for all tasks

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#284]
Even though a task may error out, as much as possible should be captured, ie:

```
 0│---
 1│exception: |-
 2│  Traceback (most recent call last):
 3│    File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 159, in run
 4│      res = self._execute()
 5│    File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 533, in _execute
 6│      self._connection = self._get_connection(cvars, templar)
 7│    File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 877, in _get_connection
 8│      connection, plugin_load_context = self._shared_loader_obj.connection_loader.get_with_context(
 9│    File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 837, in get_with_context
10│      obj.__init__(instance, *args, **kwargs)
11│    File "/usr/local/lib/python3.8/site-packages/ansible/plugins/connection/local.py", line 50, in __init__
12│      self.default_user = getpass.getuser()
13│    File "/usr/lib64/python3.8/getpass.py", line 169, in getuser
14│      return pwd.getpwuid(os.getuid())[0]
15│  KeyError: 'getpwuid(): uid not found: 1000'
16│msg: Unexpected failure during module execution.
17│stdout: ''
```
because of this failure, subsequent tasks did not run

**Comment by cidrblock** [comment]
:ee-details is gone
