### ISSUE TITLE
`:config` is failing with a stack trace

### ISSUE THREAD

**Issue by elyezer** [ansible/ansible-navigator#327]
Just pulled the latest from main, run `ansible-navigator --osc4 false`, then `:config` and got the following:

```
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/winston/bin/ansible-navigator", line 33, in <module>
    sys.exit(load_entry_point('ansible-navigator', 'console_scripts', 'ansible-navigator')())
  File "/home/elyezer/code/ansible/winston/ansible_navigator/cli.py", line 133, in main
    return_code = run(args)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/cli.py", line 74, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/action_runner.py", line 50, in run
    self._run_app(interaction)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/action_runner.py", line 59, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/config.py", line 112, in run
    self._run_runner()
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/config.py", line 212, in _run_runner
    self._parse_and_merge(list_output, dump_output)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/config.py", line 280, in _parse_and_merge
    for key, value in parsed.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by cidrblock** [comment]
@elyezer TY again, can you run with --ll debug and -la false and paste the contents of the log file here? Much appreciated

**Comment by elyezer** [comment]
It turns out that I have the following `ansible.cfg`:

```ini
option1=false
```

And the error from the log:

```
210525120541.178 ERROR 'ansible_navigator.actions.config._run_runner' Error occurred while fetching ansible config: 'Error reading config file (/home/elyezer/code/ansible/winston/ansible.cfg): File contains no section headers.
file: '<string>', line: 1
'option1=false\n'
Error reading config file (/home/elyezer/code/ansible/winston/ansible.cfg): File contains no section headers.
file: '<string>', line: 1
'option1=false\n'
'
```

It would be great if navigator was resilient to exceptions and provided some information to the user instead of a stacktrace.

**Comment by elyezer** [comment]
While running `ansible-navigator --osc4 false --ll debug --la false` with the config file without header, I found that an extra exception is being raised:

```
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/winston/bin/ansible-navigator", line 33, in <module>
    sys.exit(load_entry_point('ansible-navigator', 'console_scripts', 'ansible-navigator')())
  File "/home/elyezer/code/ansible/winston/ansible_navigator/cli.py", line 133, in main
    return_code = run(args)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/cli.py", line 74, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/action_runner.py", line 50, in run
    self._run_app(interaction)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/action_runner.py", line 59, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/config.py", line 112, in run
    self._run_runner()
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/config.py", line 212, in _run_runner
    self._parse_and_merge(list_output, dump_output)
  File "/home/elyezer/code/ansible/winston/ansible_navigator/actions/config.py", line 280, in _parse_and_merge
    for key, value in parsed.items():
AttributeError: 'NoneType' object has no attribute 'items'
Exception ignored in: <function BaseRunner.__del__ at 0x7fbf4825d4c0>
Traceback (most recent call last):
  File "/home/elyezer/code/ansible/winston/ansible_navigator/runner/api.py", line 136, in __del__
  File "/usr/lib64/python3.9/logging/__init__.py", line 1434, in debug
  File "/usr/lib64/python3.9/logging/__init__.py", line 1589, in _log
  File "/usr/lib64/python3.9/logging/__init__.py", line 1599, in handle
  File "/usr/lib64/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib64/python3.9/logging/__init__.py", line 952, in handle
  File "/usr/lib64/python3.9/logging/__init__.py", line 1186, in emit
  File "/usr/lib64/python3.9/logging/__init__.py", line 1175, in _open
NameError: name 'open' is not defined
```

And here is the complete `ansible-navigator.log` generated:

```
210525123348.272 INFO 'ansible_navigator.setup_logger' New ansible-navigator instance, logging initialized
210525123348.272 DEBUG 'ansible_navigator.main' Share directory found (development path)
210525123348.272 DEBUG 'ansible_navigator.main' Default collection_doc_cache_path set to: /home/elyezer/.cache/ansible-navigator/collection_doc_cache.db
210525123348.272 DEBUG 'ansible_navigator.main' EDITOR environment variable set as '{editor}'
210525123348.272 DEBUG 'ansible_navigator.main' Default editor_command set to: nvim {filename}
210525123348.272 DEBUG 'ansible_navigator.main' No config file set by ANSIBLE_NAVIGATOR_CONFIG
210525123348.272 DEBUG 'ansible_navigator.main' Skipping .ansible-navigator/ansible-navigator.yml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping .ansible-navigator/ansible-navigator.yaml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping .ansible-navigator/ansible-navigator.json because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /home/elyezer/code/ansible/winston/ansible_navigator/../etc/ansible-navigator/ansible-navigator.yml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /home/elyezer/code/ansible/winston/ansible_navigator/../etc/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /home/elyezer/code/ansible/winston/ansible_navigator/../etc/ansible-navigator/ansible-navigator.json because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /home/elyezer/.config/ansible-navigator/ansible-navigator.yml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /home/elyezer/.config/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /home/elyezer/.config/ansible-navigator/ansible-navigator.json because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /etc/ansible-navigator/ansible-navigator.yml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /etc/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /etc/ansible-navigator/ansible-navigator.json because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /usr/local/etc/ansible-navigator/ansible-navigator.yml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /usr/local/etc/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' Skipping /usr/local/etc/ansible-navigator/ansible-navigator.json because it does not exist
210525123348.272 DEBUG 'ansible_navigator.main' No valid config file found, using all default values for configuration.
210525123348.272 DEBUG 'ansible_navigator.main' Command provided: '--osc4 false --ll debug --la false'
210525123348.272 DEBUG 'ansible_navigator.main' Completed post processing for cmdline. (changed=False)
210525123348.272 DEBUG 'ansible_navigator.main' Completed post processing for collection_doc_cache_path. (changed=False)
210525123348.272 DEBUG 'ansible_navigator.main' Completed post processing for editor_console. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for execution_environment. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for help_config. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for help_doc. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for help_inventory. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for inventory. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for inventory_column. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for log_append. (changed=True)
210525123348.273 DEBUG 'ansible_navigator.main'  before: 'false'
210525123348.273 DEBUG 'ansible_navigator.main'  after: 'False'
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for log_file. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for mode. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for osc4. (changed=True)
210525123348.273 DEBUG 'ansible_navigator.main'  before: 'false'
210525123348.273 DEBUG 'ansible_navigator.main'  after: 'False'
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for pass_environment_variable. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for playbook. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for playbook_artifact_enable. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for playbook_artifact_replay. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for plugin_name. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Completed post processing for set_environment_variable. (changed=False)
210525123348.273 DEBUG 'ansible_navigator.main' Collection doc cache not mounted
210525123348.273 DEBUG 'ansible_navigator.main' Collection doc cache: 'path' is '/home/elyezer/.cache/ansible-navigator/collection_doc_cache.db'
210525123348.273 DEBUG 'ansible_navigator.main' Collection doc cache: 'current version' is '1.0'
210525123348.273 DEBUG 'ansible_navigator.main' Running with app as 'welcome' (str/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with cmdline as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.273 DEBUG 'ansible_navigator.main' Running with collection_doc_cache_path as '/home/elyezer/.cache/ansible-navigator/collection_doc_cache.db' (str/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with config as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.273 DEBUG 'ansible_navigator.main' Running with container_engine as 'podman' (str/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with editor_command as 'nvim {filename}' (str/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with editor_console as 'True' (bool/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with execution_environment as 'True' (bool/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with execution_environment_image as 'quay.io/ansible/ansible-runner:devel' (str/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with help_config as 'False' (bool/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with help_doc as 'False' (bool/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with help_inventory as 'False' (bool/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with inventory as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.273 DEBUG 'ansible_navigator.main' Running with inventory_column as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.273 DEBUG 'ansible_navigator.main' Running with log_append as 'False' (bool/cli parameters)
210525123348.273 DEBUG 'ansible_navigator.main' Running with log_file as '/home/elyezer/code/ansible/winston/ansible-navigator.log' (str/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with log_level as 'debug' (str/cli parameters)
210525123348.273 DEBUG 'ansible_navigator.main' Running with mode as 'interactive' (str/default configuration value)
210525123348.273 DEBUG 'ansible_navigator.main' Running with osc4 as 'False' (bool/cli parameters)
210525123348.273 DEBUG 'ansible_navigator.main' Running with pass_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.273 DEBUG 'ansible_navigator.main' Running with playbook as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.273 DEBUG 'ansible_navigator.main' Running with playbook_artifact_enable as 'True' (bool/default configuration value)
210525123348.274 DEBUG 'ansible_navigator.main' Running with playbook_artifact_replay as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.274 DEBUG 'ansible_navigator.main' Running with playbook_artifact_save_as as '{playbook_dir}/{playbook_name}-artifact-{ts_utc}.json' (str/default configuration value)
210525123348.274 DEBUG 'ansible_navigator.main' Running with plugin_name as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.274 DEBUG 'ansible_navigator.main' Running with plugin_type as 'module' (str/default configuration value)
210525123348.274 DEBUG 'ansible_navigator.main' Running with pull_policy as 'tag' (str/default configuration value)
210525123348.274 DEBUG 'ansible_navigator.main' Running with set_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)
210525123348.276 INFO 'ansible_navigator.image_manager.image_puller._log_message' Image tag is: devel
210525123348.383 DEBUG 'ansible_navigator.ui_framework.ui._set_colors' curses.COLORS: 256
210525123348.383 DEBUG 'ansible_navigator.ui_framework.ui._set_colors' curses.can_change_color: True
210525123348.383 DEBUG 'ansible_navigator.ui_framework.ui._set_colors' self._osc4: False
210525123348.383 DEBUG 'ansible_navigator.ui_framework.ui._set_colors' _custom_colors_enabled: False
210525123348.383 DEBUG 'ansible_navigator.ui_framework.ui._set_colors' Using terminal defaults
210525123348.480 DEBUG 'ansible_navigator.actions.welcome.run' welcome requested
210525123351.269 DEBUG 'ansible_navigator.actions.config.run' config requested in interactive mode
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' No config file set by ANSIBLE_NAVIGATOR_CONFIG
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping .ansible-navigator/ansible-navigator.yml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping .ansible-navigator/ansible-navigator.yaml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping .ansible-navigator/ansible-navigator.json because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /home/elyezer/code/ansible/winston/ansible_navigator/../etc/ansible-navigator/ansible-navigator.yml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /home/elyezer/code/ansible/winston/ansible_navigator/../etc/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /home/elyezer/code/ansible/winston/ansible_navigator/../etc/ansible-navigator/ansible-navigator.json because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /home/elyezer/.config/ansible-navigator/ansible-navigator.yml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /home/elyezer/.config/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /home/elyezer/.config/ansible-navigator/ansible-navigator.json because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /etc/ansible-navigator/ansible-navigator.yml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /etc/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /etc/ansible-navigator/ansible-navigator.json because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /usr/local/etc/ansible-navigator/ansible-navigator.yml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /usr/local/etc/ansible-navigator/ansible-navigator.yaml because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Skipping /usr/local/etc/ansible-navigator/ansible-navigator.json because it does not exist
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' No valid config file found, using all default values for configuration.
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Command provided: 'config'
210525123351.276 INFO 'ansible_navigator.actions.config._update_args' 'mode' cannot be reconfigured. (restore original)
210525123351.276 INFO 'ansible_navigator.actions.config._update_args' 'mode' cannot be reconfigured. (apply defaults)
210525123351.276 INFO 'ansible_navigator.actions.config._update_args' 'mode' cannot be reconfigured (apply previous cli)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for cmdline. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for collection_doc_cache_path. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for editor_console. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for execution_environment. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for help_config. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for help_doc. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for help_inventory. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for inventory. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for inventory_column. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for log_append. (changed=False)
210525123351.276 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for log_file. (changed=False)
210525123351.276 INFO 'ansible_navigator.actions.config._update_args' 'mode' cannot be reconfigured. (post process)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for osc4. (changed=False)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for pass_environment_variable. (changed=False)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for playbook. (changed=False)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for playbook_artifact_enable. (changed=False)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for playbook_artifact_replay. (changed=False)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for plugin_name. (changed=False)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Completed post processing for set_environment_variable. (changed=False)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with app as 'config' (str/cli parameters)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with cmdline as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with collection_doc_cache_path as '/home/elyezer/.cache/ansible-navigator/collection_doc_cache.db' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with config as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with container_engine as 'podman' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with editor_command as 'nvim {filename}' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with editor_console as 'True' (bool/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with execution_environment as 'True' (bool/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with execution_environment_image as 'quay.io/ansible/ansible-runner:devel' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with help_config as 'False' (bool/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with help_doc as 'False' (bool/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with help_inventory as 'False' (bool/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with inventory as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with inventory_column as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with log_append as 'False' (bool/previous cli command)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with log_file as '/home/elyezer/code/ansible/winston/ansible-navigator.log' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with log_level as 'debug' (str/previous cli command)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with mode as 'interactive' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with osc4 as 'False' (bool/previous cli command)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with pass_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with playbook as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with playbook_artifact_enable as 'True' (bool/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with playbook_artifact_replay as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with playbook_artifact_save_as as '{playbook_dir}/{playbook_name}-artifact-{ts_utc}.json' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with plugin_name as 'Constants.NOT_SET' (Constants/value has not been set)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with plugin_type as 'module' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with pull_policy as 'tag' (str/default configuration value)
210525123351.277 DEBUG 'ansible_navigator.actions.config._update_args' Running with set_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)
210525123352.784 DEBUG 'ansible_navigator.runner.api.runner_artifacts_handler' ansible-runner artifact_dir set to: '/tmp/ansible-navigator/artifacts/6449191e-a059-49e7-ac20-db7d8a4a74e0'
210525123354.259 DEBUG 'ansible_navigator.runner.api.runner_artifacts_handler' ansible-runner artifact_dir set to: '/tmp/ansible-navigator/artifacts/56290aad-d0f7-427f-a65a-679ad8b82c58'
210525123354.259 ERROR 'ansible_navigator.actions.config._run_runner' Error occurred while fetching ansible config: 'Error reading config file (/home/elyezer/code/ansible/winston/ansible.cfg): File contains no section headers.
file: '<string>', line: 1
'option1=false\n'
Error reading config file (/home/elyezer/code/ansible/winston/ansible.cfg): File contains no section headers.
file: '<string>', line: 1
'option1=false\n'
'
210525123354.259 DEBUG 'ansible_navigator.actions.config._parse_and_merge' yaml loading list output succeeded
```

**Comment by cidrblock** [comment]
Nice find, yeah a traceback is terrible.  We can do this instead: 
![image](https://user-images.githubusercontent.com/18386516/119733402-50e6ad00-be2e-11eb-842f-f3d011fcc84a.png)

**Comment by justjais** [comment]
@cidrblock This also happens when the CE type is podman and which cannot connect to the podman socket, ref Traceback:

```
Traceback (most recent call last):
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/bin/ansible-navigator", line 10, in <module>
    sys.exit(main())
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/cli.py", line 104, in main
    run(args)
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/cli.py", line 54, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/action_runner.py", line 50, in run
    self._run_app(interaction)
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/action_runner.py", line 59, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/actions/_actions.py", line 95, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/actions/config.py", line 107, in run
    self._run_runner()
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/actions/config.py", line 203, in _run_runner
    self._parse_and_merge(list_output, dump_output)
  File "/Users/sjaiswal/Sumit/ansible_fork/ansible_navigator_test/venv/lib/python3.7/site-packages/ansible_navigator/actions/config.py", line 260, in _parse_and_merge
    for key, value in parsed.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

But the navigator log does show more informative error:
```
210528082153.773 ERROR 'ansible_navigator.actions.config._run_runner' Error occurred while fetching ansible config: 'Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v3.1.2/libpod/_ping": dial unix ///var/folders/_0/m716s5gx1g3d5j1dw_s2w1ph0000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

Ideally this should be thrown as exception rather than py traceback.
