### ISSUE TITLE
During a playbook run, if User go to some those options(:collections/:config/:images/) and stay until the playbook finished, an error will occur

### ISSUE THREAD

**Issue by yagomarques** [ansible/ansible-navigator#414]
During a playbook run, if User go to some those options(:collections/:config/:images/) and stay until the playbook finished, an error will occur

1. run a playbook using the TUI
2. while the playbook is running, go to one of those options: `:collections/:config/:images/`
3. stay until the playbook finished
4. an error occurs.
```
Traceback (most recent call last):
  File "/home/yagosilva/venvs/navigator/bin/ansible-navigator", line 33, in <module>
    sys.exit(load_entry_point('ansible-navigator', 'console_scripts', 'ansible-navigator')())
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/cli.py", line 137, in main
    return_code = run(args)
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/cli.py", line 81, in run
    wrapper(ActionRunner(args=args).run)
  File "/home/yagosilva/.pyenv/versions/3.9.0/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/action_runner.py", line 65, in run
    self._run_app(interaction)
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/action_runner.py", line 74, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/actions/run.py", line 300, in run
    self._take_step()
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/actions/run.py", line 516, in _take_step
    result = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/actions/config.py", line 130, in run
    self._calling_app.update()
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/actions/run.py", line 772, in update
    self.write_artifact()
  File "/home/yagosilva/projects/ansible-navigator/ansible_navigator/actions/run.py", line 817, in write_artifact
    playbook_dir=os.path.dirname(self._args.playbook),
  File "/home/yagosilva/.pyenv/versions/3.9.0/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not Constants
```

**Comment by cidrblock** [comment]
This is because args is passed by reference to another action and modified there.  We keep the "previous entries" and restore them when exiting the action, will need to talk about how best to solve this, maybe self._args should also be a deepcopy?
