### ISSUE TITLE
[configuration] Traceback if no share directory found

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#433]
```
(py38) ➜  ansible-navigator git:(main) python -m ansible_navigator 
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/bthornto/github/ansible-navigator/ansible_navigator/__main__.py", line 5, in <module>
    main()
  File "/Users/bthornto/github/ansible-navigator/ansible_navigator/cli.py", line 98, in main
    new_messages, new_exit_messages = parse_and_update(sys.argv[1:], args=args, initial=True)
  File "/Users/bthornto/github/ansible-navigator/ansible_navigator/initialization.py", line 194, in parse_and_update
    new_messages, new_exit_messages, cache = get_and_check_collection_doc_cache(
  File "/Users/bthornto/github/ansible-navigator/ansible_navigator/initialization.py", line 113, in get_and_check_collection_doc_cache
    collection_cache = _get_kvs(share_directory, collection_doc_cache_path)
  File "/Users/bthornto/github/ansible-navigator/ansible_navigator/initialization.py", line 136, in _get_kvs
    spec_path = os.path.join(share_directory, "utils", "key_value_store.py")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by cidrblock** [comment]
(from adam mack)
