### ISSUE TITLE
:doc is not working on a fresh install

### ISSUE THREAD

**Issue by elyezer** [ansible/ansible-navigator#44]
I've just installed winston and ran it. Then trying to execute `:doc` from the main screen is raising the following exception:

```
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/winston/bin/winston", line 33, in <module>
    sys.exit(load_entry_point('winston', 'console_scripts', 'winston')())
  File "/home/elyezer/code/ansible/winston/winston/cli.py", line 294, in main
    run(args)
  File "/home/elyezer/code/ansible/winston/winston/cli.py", line 260, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/elyezer/code/ansible/winston/winston/action_runner.py", line 51, in run
    self._run_app(interaction)
  File "/home/elyezer/code/ansible/winston/winston/action_runner.py", line 60, in _run_app
    interaction = run_action(
  File "/home/elyezer/code/ansible/winston/winston/actions/_actions.py", line 68, in call
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/elyezer/code/ansible/winston/winston/actions/doc.py", line 45, in run
    plugin = interaction.content.showing["task_action"]
TypeError: string indices must be integers
```

I am currently trying on Python 3.9 on Fedora 33.

**Comment by cidrblock** [comment]
this now fails gracefully if no plugin for doc is provided and logs to the application log

```
179│210503212143.316 ERROR 'ansible_navigator.actions.doc._update_args' An plugin name is required when using the doc subcommand
180│210503212143.316 INFO 'ansible_navigator.actions.doc.run' No plugin name found in current content```

fixed in #167
