### ISSUE TITLE
KeyError exception when trying to browse group on inventory

### ISSUE THREAD

**Issue by elyezer** [ansible/ansible-navigator#45]
I have run `:inventory`  then filled the path to the following inventory on the form and submitted it.

```ini
[all]
ec2-54-86-73-255.compute-1.amazonaws.com ansible_user=ec2-user ansible_host=54.86.73.255 ansible_python_interpreter="/usr/libexec/platform-python"
localhost ansible_connection=local ansible_python_interpreter="/usr/libexec/platform-python"

[ungrouped]

[local]
localhost ansible_connection=local ansible_python_interpreter="/usr/libexec/platform-python"

[cloud]
ec2-54-86-73-255.compute-1.amazonaws.com ansible_user=ec2-user ansible_host=54.86.73.255 ansible_python_interpreter="/usr/libexec/platform-python"

[ec2]
ec2-54-86-73-255.compute-1.amazonaws.com ansible_user=ec2-user ansible_host=54.86.73.255 ansible_python_interpreter="/usr/libexec/platform-python"

[rhel-8.3-x86_64]
ec2-54-86-73-255.compute-1.amazonaws.com ansible_user=ec2-user ansible_host=54.86.73.255 ansible_python_interpreter="/usr/libexec/platform-python"

[tower]
ec2-54-86-73-255.compute-1.amazonaws.com ansible_user=ec2-user ansible_host=54.86.73.255 ansible_python_interpreter="/usr/libexec/platform-python"

[instance_group_non_default]
ec2-54-86-73-255.compute-1.amazonaws.com ansible_user=ec2-user ansible_host=54.86.73.255 ansible_python_interpreter="/usr/libexec/platform-python"
```

Then selected `0 Browse Groups` and then `0 cloud` and the following exception was raised:

```
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/winston/bin/winston", line 33, in <module>
    sys.exit(load_entry_point('winston', 'console_scripts', 'winston')())
  File "/home/elyezer/code/ansible/winston/winston/cli.py", line 294, in main
    run(args)
  File "/home/elyezer/code/ansible/winston/winston/cli.py", line 260, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/elyezer/code/ansible/winston/winston/action_runner.py", line 51, in run
    self._run_app(interaction)
  File "/home/elyezer/code/ansible/winston/winston/action_runner.py", line 60, in _run_app
    interaction = run_action(
  File "/home/elyezer/code/ansible/winston/winston/actions/_actions.py", line 68, in call
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/elyezer/code/ansible/winston/winston/actions/inventory.py", line 193, in run
    self._take_step()
  File "/home/elyezer/code/ansible/winston/winston/actions/inventory.py", line 241, in _take_step
    result = self._interaction.ui.show(
  File "/home/elyezer/code/ansible/winston/winston/ui_framework/ui.py", line 855, in show
    result = self._show_menu(obj, columns, await_input)
  File "/home/elyezer/code/ansible/winston/winston/ui_framework/ui.py", line 790, in _show_menu
    menu_heading, menu_lines = self._get_heading_menu_items(current, columns, showing_idxs)
  File "/home/elyezer/code/ansible/winston/winston/ui_framework/ui.py", line 750, in _get_heading_menu_items
    menu_heading, menu_items = menu_builder.build(
  File "/home/elyezer/code/ansible/winston/winston/ui_framework/menu_builder.py", line 39, in build
    return self._menu(dicts, cols, indicies)
  File "/home/elyezer/code/ansible/winston/winston/ui_framework/menu_builder.py", line 56, in _menu
    convert_percentage(dicts[idx], cols, self._pbar_width)
  File "/home/elyezer/code/ansible/winston/winston/ui_framework/utils.py", line 23, in convert_percentage
    value = dyct[key]
KeyError: ''
```

**Comment by cidrblock** [comment]
fixed
