### ISSUE TITLE
[:images] On RHEL+Selinux - the Ansible-navigator being installed in /usr creates an Error: relabeling content in /usr is not allowed

### ISSUE THREAD

**Issue by yagomarques** [ansible/ansible-navigator#490]
##### ISSUE TYPE
 - Bug Report

##### Informations
to reproduce the follow error on RHEL:

1. install navigator using the RPM
2. access the :images
3. choose an image
4. choose one of those options
```
1│General information                                                  OS and python version information
2│Ansible version and collections                                      Information about ansible and ansible collections
3│Python packages                                                      Information about python and python packages
4│Operating system packages                                            Information about operating system packages
5│Everything         
```
4 - this error will occurs:
```
Traceback (most recent call last):
  File "/usr/bin/ansible-navigator", line 11, in <module>
    load_entry_point('ansible-navigator==1.0.0rc2', 'console_scripts', 'ansible-navigator')()
  File "/usr/lib/python3.8/site-packages/ansible_navigator/cli.py", line 142, in main
    return_code = run(args)
  File "/usr/lib/python3.8/site-packages/ansible_navigator/cli.py", line 83, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.8/site-packages/ansible_navigator/action_runner.py", line 65, in run
    self._run_app(interaction)
  File "/usr/lib/python3.8/site-packages/ansible_navigator/action_runner.py", line 74, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/usr/lib/python3.8/site-packages/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/usr/lib/python3.8/site-packages/ansible_navigator/actions/images.py", line 149, in run
    self._take_step()
  File "/usr/lib/python3.8/site-packages/ansible_navigator/actions/images.py", line 164, in _take_step
    result = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/usr/lib/python3.8/site-packages/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/usr/lib/python3.8/site-packages/ansible_navigator/actions/select.py", line 37, in run
    app.steps.append(app.steps.current.select_func())  # add next
  File "/usr/lib/python3.8/site-packages/ansible_navigator/actions/images.py", line 210, in _build_image_content
    self._introspect_image()
  File "/usr/lib/python3.8/site-packages/ansible_navigator/actions/images.py", line 371, in _introspect_image
    "os": parsed["os_release"],
TypeError: 'NoneType' object is not subscriptable
```
the error above is because the introspection of the image failed (there was no os_release information pulled from it)

So, we run the next command to introspect the container and we saw the problem
```
[brad@tower ~]$ podman run --rm --tty --interactive --workdir /runner/project --group-add=root --userns=keep-id --ipc=host -v /tmp/ansible-navigator/artifacts/:/runner/artifacts/:Z -v /tmp/ansible-navigator/:/runner/:Z -v /usr/share/ansible_navigator/utils/:/usr/share/ansible_navigator/utils/:z --env-file /tmp/ansible-navigator/artifacts/4dddf017-2bbd-478a-97af-47a0343ecb6e/env.list --quiet --name ansible_runner_4dddf017-2bbd-478a-97af-47a0343ecb6e quay.io/ansible/ansible-navigator-demo-ee:0.4.0 python3 /usr/share/ansible_navigator/utils/image_introspect.py
Error: relabeling content in /usr is not allowed

```
##### ANSIBLE-NAVIGATOR VERSION
`ansible-navigator 1.0.0rc2`

##### LOG FILE
```
210623143848.615 ERROR 'ansible_navigator.actions.collections._parse' Unable to extract collection json from stdout
210623143927.276 WARNING 'ansible_navigator.actions.doc._update_args' Configuration errors encountered, rolling back to previous configuration.
210623143927.276 WARNING 'ansible_navigator.actions.doc._update_args' Command provided: 'doc'
210623143927.276 WARNING 'ansible_navigator.actions.doc._update_args' A plugin name is required when using the doc subcommand
210623143942.414 WARNING 'ansible_navigator.actions.doc._update_args' Configuration errors encountered, rolling back to previous configuration.
210623143942.415 WARNING 'ansible_navigator.actions.doc._update_args' Command provided: 'doc'
210623143942.415 WARNING 'ansible_navigator.actions.doc._update_args' A plugin name is required when using the doc subcommand
210623144006.449 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
210623144019.502 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
210623144029.944 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
210623144449.737 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
210623144459.904 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
210623145113.750 CRITICAL 'ansible_navigator.actions.run_da0c._handle_message' Unhandled message from runner queue, discarded: {'uuid': '0f4b26de-ae2e-422d-b792-51b5bc98694f', 'counter': 12, 'stdout': '', 'start_line': 11, 'end_line': 11, 'runner_ident': '36a0337f-5d4e-4e53-becf-56eab02e90b8', 'created': '2021-06-23T14:51:13.734467'}
210623145113.751 CRITICAL 'ansible_navigator.actions.run_da0c._handle_message' Unhandled message from runner queue, discarded: {'uuid': '2e7bdcaf-79c6-9b87-0a8e-000000000005', 'counter': 13, 'stdout': '\r\nPLAY [all] *********************************************************************', 'start_line': 11, 'end_line': 13, 'runner_ident': '36a0337f-5d4e-4e53-becf-56eab02e90b8', 'created': '2021-06-23T14:51:13.736665'}
210623145113.751 CRITICAL 'ansible_navigator.actions.run_da0c._handle_message' Unhandled message from runner queue, discarded: {'uuid': '2df6d3f3-43e3-4cb6-94a5-c9ad53d94818', 'counter': 14, 'stdout': '\x1b[0;36mskipping: no hosts matched\x1b[0m', 'start_line': 13, 'end_line': 14, 'runner_ident': '36a0337f-5d4e-4e53-becf-56eab02e90b8', 'created': '2021-06-23T14:51:13.737575'}
210623145113.751 CRITICAL 'ansible_navigator.actions.run_da0c._handle_message' Unhandled message from runner queue, discarded: {'uuid': '82a606f7-4a85-484d-bc13-33b97227311f', 'counter': 15, 'stdout': '\r\nPLAY RECAP *********************************************************************\r\n', 'start_line': 14, 'end_line': 17, 'runner_ident': '36a0337f-5d4e-4e53-becf-56eab02e90b8', 'created': '2021-06-23T14:51:13.738072'}
```

##### EXPECTED RESULTS
See the image's details correctly
##### ACTUAL RESULTS
the error above occurs

**Comment by yagomarques** [comment]
it's working, i ran the same scenarios on the new version.

![image](https://user-images.githubusercontent.com/18562328/123302821-7b8e5900-d4f3-11eb-8dfb-c59345f6697e.png)
