### ISSUE TITLE
RPM installed ansible and ansible-navigator, collection cataloging fails when execution-environment=False

### ISSUE THREAD

**Issue by yagomarques** [ansible/ansible-navigator#503]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
RPM installed ansible and ansible-navigator, collection cataloging fails when execution-environment=False, because when runner runs the catalog collection script the import of ansible fails.

##### LOG FILE
```
210624202944.120 ERROR 'ansible_navigator.actions.collections._parse' Unable to extract collection json from stdout
210624202944.120 DEBUG 'ansible_navigator.actions.collections._parse' error json loading output: 'not enough values to unpack (expected 2, got 1)'
210624202944.120 DEBUG 'ansible_navigator.actions.collections._parse' Traceback (most recent call last):
  File "/usr/share/ansible_navigator/utils/catalog_collections.py", line 22, in <module>
    from ansible.utils.plugin_docs import get_docstring  # type: ignore
ModuleNotFoundError: No module named 'ansible'
```

##### STEPS TO REPRODUCE
**On RHEL**
1. there is a RHEL machine with ansible-navigator installed with RPM
2. run the command `ansible-navigator collections --ee false --ll debug --la false`
3. check the logs, you will see the error.
##### EXPECTED RESULTS

Show all collections installed locally 

##### ACTUAL RESULTS
Costumer cant see all collections installed locally

##### ADDITIONAL INFORMATION
We should be able to reproduce the same error on Fedora, but the process and the cause is other.
to reproduce:

1. install `pip install ansible` without a virtual environment
2. python3 -m venv venv
3. source venv/bin/activate
4. pip install ansible-navigator
5. `ansible-navigator collections --ee false --ll debug --la false`
6. check the error:
```
210624204127.219 ERROR 'ansible_navigator.actions.collections._parse' Unable to extract collection json from stdout
210624204127.220 DEBUG 'ansible_navigator.actions.collections._parse' error json loading output: 'not enough values to unpack (expected 2, got 1)'
210624204127.220 DEBUG 'ansible_navigator.actions.collections._parse' Traceback (most recent call last):
  File "/home/yagosilva/projects/ansible-navigator/share/ansible_navigator/utils/catalog_collections.py", line 22, in <module>
    from ansible.utils.plugin_docs import get_docstring  # type: ignore
ModuleNotFoundError: No module named 'ansible'
```
the scenario:
```
(navigator)  yagosilva@localhost  ~/projects  which ansible
/usr/local/bin/ansible
(navigator)  yagosilva@localhost  ~/projects  which ansible-navigator 
~/venvs/navigator/bin/ansible-navigator
```

talking to Brad, this error on Fedora could be something more related a python issue, the venv doesn't really know about the other stuff installed. if you built the venv with `  --system-site-packages` it might work

**Comment by webknjaz** [comment]
The pip-based STR is different and expected. We may want to provide an extra dependency but it is out of the scope in this bug report.

I've attempted to reproduce it on a @IPvSean-provided RHEL box and it doesn't error out as described in the report above.

The version of ansible-navigator present there is
```console
Installed Packages
Name         : ansible-navigator
Version      : 1.0.0
Release      : 2.el8ap
Architecture : noarch
Size         : 1.1 M
Source       : ansible-navigator-1.0.0-2.el8ap.src.rpm
Repository   : @System
From repo    : aap_installer
Summary      : Red Hat Ansible Automation Platform CLI
URL          : https://github.com/ansible/ansible-navigator
License      : ASL 2.0
Description  : A TUI for the Red Hat Ansible Automation Platform
```

And the version of ansible-core is
```console
Name         : ansible-core
Version      : 2.11.2
Release      : 2.el8ap
Architecture : x86_64
Size         : 9.2 M
Source       : ansible-core-2.11.2-2.el8ap.src.rpm
Repository   : @System
From repo    : aap_installer
Summary      : SSH-based configuration management, deployment, and task
             : execution system
URL          : http://ansible.com
License      : GPLv3+
Description  : Ansible is a radically simple model-driven configuration
             : management, multi-node deployment, and remote task execution
             : system. Ansible works over SSH and does not require any
             : software or daemons to be installed on remote nodes. Extension
             : modules can be written in any language and are transferred to
```

Note that this issue has been reported a few days before ansible-navigator v1.0.0 was released. So it was reproducible in some older versions but @yagomarques didn't mention which one. They also didn't mention which version of Ansible or ansible-core was present in their environment.

So there's a chance that it's not an issue anymore in the latest version.

**Comment by webknjaz** [comment]
I uninstalled ansible-core and then I was able to reproduce the bug by installing Ansible 2.9 instead:
```console
Name         : ansible
Version      : 2.9.25
Release      : 1.el8
Architecture : noarch
Size         : 96 M
Source       : ansible-2.9.25-1.el8.src.rpm
Repository   : @System
From repo    : epel
Summary      : SSH-based configuration management, deployment, and task
             : execution system
URL          : http://ansible.com
License      : GPLv3+
Description  : Ansible is a radically simple model-driven configuration
             : management, multi-node deployment, and remote task execution
             : system. Ansible works over SSH and does not require any
             : software or daemons to be installed on remote nodes. Extension
             : modules can be written in any language and are transferred to
             : managed machines automatically.
```

My initial packaging hunch was right — it is indeed happening because pre-collection-split Ansible versions are installed under Python 3.6 (the default system Python) and ansible-core+ (and all of its dependencies) is installed under Python 3.8 (usually available from an additional repository).

```console
# ansible-navigator v1.0.0:
$ head -n1 $(which ansible-navigator)
#!/usr/bin/python3.8
$ # ansible-core v2.11.2:
$ head -n1 $(which ansible-playbook)
#!/usr/bin/python3.8
$ # Ansible v2.9.25:
$ head -n1 $(which ansible-playbook)
#!/usr/bin/python3.6
```

I wonder what we'll want to do about this, though.

**Comment by webknjaz** [comment]
The most reasonable solution for us seems to be to rely on the shebang of the `ansible-playbook` executable on the local file system.
