### ISSUE TITLE
Image information fails

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible-navigator#517]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When trying to get `Image information` from `ansible-navigator images` for example `ansible-navigator-demo-ee` it throws an exception.
##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.0.0
```

##### LOG FILE

`210727084516.880 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed`
##### STEPS TO REPRODUCE
Try to get `Image information` from any image.

##### ACTUAL RESULTS
```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/ansible-navigator", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/cli.py", line 142, in main
    return_code = run(args)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/cli.py", line 83, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 65, in run
    self._run_app(interaction)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 74, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/images.py", line 149, in run
    self._take_step()
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/images.py", line 185, in _take_step
    filter_content_keys=filter_content_keys,
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 885, in show
    result = self._show_obj_from_list([obj], 0, await_input)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 643, in _show_obj_from_list
    heading, lines = self._filter_and_serialize(objs[index])
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 622, in _filter_and_serialize
    lines = self._serialize_color(filtered_obj)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 513, in _serialize_color
    string = human_dump(obj)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/yaml.py", line 44, in human_dump
    return yaml.dump(obj, Dumper=dumper, **YamlStyle()._asdict())
  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```

**Comment by cidrblock** [comment]
https://github.com/ansible/ansible-navigator/issues/525

likely related
