### ISSUE TITLE
Selecting "General information" in `ansible-navigator images` fails with traceback

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible-navigator#518]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When running the `General information` from `ansible-navigator images` it first time fails with WARNING `Something went really wrong while introspecting the image.`... providing log below.
And when I try it once again it fails with the error in `ACTUAL RESULTS`
Sometimes it fails with the error in #517 depending on the image.
For example, the `ansible-navigator-demo-ee` throws this error but `ansible-runner` image throws #517.
##### ANSIBLE-NAVIGATOR VERSION

```

```

##### LOG FILE

```
210727103627.837 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
210727103627.838 ERROR 'ansible_navigator.actions.images._introspect_image' Image introspection failed (parsed), the return value was: Error: container_linux.go:367: starting container process caused: chdir to cwd ("/runner/project") set in config.json failed: permission denied: OCI permission denied
```
##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-navigator", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/cli.py", line 142, in main
    return_code = run(args)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/cli.py", line 83, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 65, in run
    self._run_app(interaction)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 74, in _run_app
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/images.py", line 149, in run
    self._take_step()
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/images.py", line 164, in _take_step
    result = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/_actions.py", line 97, in run_interactive
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/select.py", line 37, in run
    app.steps.append(app.steps.current.select_func())  # add next
  File "/usr/local/lib/python3.6/site-packages/ansible_navigator/actions/images.py", line 218, in _build_image_content
    value=self._images.selected["general"],
KeyError: 'general'
```

**Comment by relrod** [comment]
Is this still an issue? I can't reproduce this on any of the EEs that I have locally (I tried a fair number on both podman and docker).

**Comment by shatakshiiii** [comment]
Hi @mnecas ! I'm not able to reproduce this with the latest version of navigator. Can you please confirm and let us know if you are still getting this issue with ansible-navigator 3.3.1 ?
