### ISSUE TITLE
Stack trace when going into collections>collection>module

### ISSUE THREAD

**Issue by termlen0** [ansible/ansible-navigator#522]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Within navigator, invoking collections followed by ios.cisco.ios followed by ios_command results in a stack trace

##### ANSIBLE-NAVIGATOR VERSION

```console
1.0.0
```

##### CONFIGURATION

```yaml
---
ansible-navigator:
  ansible:
    config: ansible.cfg
  execution-environment:
    image: iossnow:latest
    #container-engine: podman
    pull-policy: never
  editor:
    command: code -g {filename}:{line_number}
    console: false
  logging:
    level: critical

```
##### LOG FILE

See stack trace in actual results below

##### STEPS TO REPRODUCE

`:collections > cisco.ios > ios_command`
##### EXPECTED RESULTS

Module details

##### ACTUAL RESULTS

```python-traceback
Traceback (most recent call last):
  File "/home/student1/demo/bin/ansible-navigator", line 8, in <module>
    sys.exit(main())
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/cli.py", line 142, in main
    return_code = run(args)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/cli.py", line 83, in run
    wrapper(ActionRunner(args=args).run)
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 65, in run
    self._run_app(interaction)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/action_runner.py", line 74, in _run_app                                                                         
    interaction = run_action(self.steps.current.name, self.app, self.steps.current)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/actions/_actions.py", line 97, in run_interactive                                                               
    return action_cls(app.args).run(app=app, interaction=interaction)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/actions/collections.py", line 138, in run                                                                       
    self._take_step()
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/actions/collections.py", line 171, in _take_step                                                                
    filter_content_keys=filter_content_keys,
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 881, in show                                                                          
    result = self._show_obj_from_list(obj, index, await_input)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 643, in _show_obj_from_list                                                           
    heading, lines = self._filter_and_serialize(objs[index])
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 622, in _filter_and_serialize                                                         
    lines = self._serialize_color(filtered_obj)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/ui_framework/ui.py", line 513, in _serialize_color                                                              
    string = human_dump(obj)
  File "/home/student1/demo/lib/python3.6/site-packages/ansible_navigator/yaml.py", line 44, in human_dump                                                                                
    return yaml.dump(obj, Dumper=dumper, **YamlStyle()._asdict())
  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```

**Comment by cidrblock** [comment]
https://github.com/ansible/ansible-navigator/issues/525

likely related
