### ISSUE TITLE
Using --become-vault-pass throws an exception

### ISSUE THREAD

**Issue by lotaris-xx** [ansible/ansible-navigator#998]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

```python-traceback
$ ansible-navigator run main.yml -i inventories --become-pass-file vpass -vvv --mode=stdout
ansible-playbook [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
ERROR! Unexpected Exception, this is probably a bug: module 'posixpath' has no attribute 'is_executable'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 128, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.8/site-packages/ansible/cli/playbook.py", line 114, in run
    (sshpass, becomepass) = self.ask_passwords()
  File "/usr/lib/python3.8/site-packages/ansible/cli/__init__.py", line 264, in ask_passwords
    becomepass = CLI.get_password_from_file(op['become_password_file'])
  File "/usr/lib/python3.8/site-packages/ansible/cli/__init__.py", line 516, in get_password_from_file
    elif os.path.is_executable(b_pwd_file):
AttributeError: module 'posixpath' has no attribute 'is_executable'
```

##### ANSIBLE-NAVIGATOR VERSION

```console
ansible-navigator 1.1.0
```

##### CONFIGURATION
```yaml
---
ansible-navigator:
  color:
    enable: True
    osc4: True
  execution-environment:
    container-engine: podman
    enabled: True
    image: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest
    pull-policy: missing
  logging:
    level: debug
  playbook-artifact:
    enable: False
    replay: /tmp/hello_artifact.json
    save-as: /tmp/hello_artifact.json
```

##### STEPS TO REPRODUCE

1) put something in a password file (vpass in this example)
2) `ansible-navigator run main.yml -i inventories --become-pass-file vpass -vvv --mode=stdout`

##### EXPECTED RESULTS

Expect it to use the password from that file.

##### ACTUAL RESULTS

```python-traceback
ERROR! Unexpected Exception, this is probably a bug: module 'posixpath' has no attribute 'is_executable'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 128, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.8/site-packages/ansible/cli/playbook.py", line 114, in run
    (sshpass, becomepass) = self.ask_passwords()
  File "/usr/lib/python3.8/site-packages/ansible/cli/__init__.py", line 264, in ask_passwords
    becomepass = CLI.get_password_from_file(op['become_password_file'])
  File "/usr/lib/python3.8/site-packages/ansible/cli/__init__.py", line 516, in get_password_from_file
    elif os.path.is_executable(b_pwd_file):
AttributeError: module 'posixpath' has no attribute 'is_executable'
```

**Comment by webknjaz** [comment]
The `AttributeError` is legit. Here's what I got on my Gentoo laptop:
```python-traceback
$ python                         
Python 3.10.1 (main, Dec 14 2021, 13:31:42) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.is_executable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'posixpath' has no attribute 'is_executable'
```
Right now, it looks like an `ansible-core` bug.

**Comment by webknjaz** [comment]
I see that ansible/ansible@devel has this on that line:
```diff
-    elif os.path.is_executable(b_pwd_file):
+    elif is_executable(b_pwd_file):
```
This probably means that it's been fixed in a newer version. Let me dig a bit.

**Comment by webknjaz** [comment]
The upstream bug https://github.com/ansible/ansible/issues/76530 has been fixed by https://github.com/ansible/ansible/pull/76534 2 months ago.

**Comment by webknjaz** [comment]
It was backported as https://github.com/ansible/ansible/pull/76558 and is included with `ansible-core >= 2.12.2`: https://github.com/ansible/ansible/blob/v2.12.2/lib/ansible/cli/__init__.py#L517.

**Comment by webknjaz** [comment]
Nothing to do on our side. @lotaris-xx you can get the fix by updating `ansible-core` in the image.

**Comment by cidrblock** [comment]
@lotaris-xx I see you are using the support platform execution environment.  Let me research what the latest release of the EE has in it.  You shouldn't need to have to worry about updating ansible-core in the EE.
